server:
  #单点登录模块服务端口
  port: 8091

spring:
  #模块名
  application:
    name: hbuy_sso
  mvc:
    #配置静态资源的访问路径
    static-path-pattern: /static/**
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x9505_hbuy?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  thymeleaf:
    #不使用页面缓存
    cache: false
    #访问thymeleaf模板页面的路径前缀
    prefix: classpath:/templates/
    #访问thymeleaf模板页面的路径后缀
    suffix: .html
    #使用的文件类型
    mode: HTML5
    #文件的字符编码
    encoding: UTF-8
    servlet:
      #文件的内容类型
      content-type: text/html

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

redis:
#使用的redis的库
  database: 0
#访问的ip
  host: 127.0.0.1
#访问端口
  port: 6379
#链接时间
  timeout: 3000

#配置mybatis
mybatis:
  #配置实体封装类别名
  type-aliases-package: com.java.model
  configuration:
    #在控制台中输出mybatis相关日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    #cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      #配置注册路径
      defaultZone: http://127.0.0.1:10086/eureka
